name: Front tests

on:
  push:
    paths:
      - '.github/**'
      - 'frontend/**'
    pull_request:
      branches:
        - master
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - run: ls -l
    - run: npm -v

    - name:
      run: npm i -g @angular/cli@9.0.3

    - name: Install packages
      run: npm i
      working-directory: ${{env.working-directory}}

    - name: Run tests
      run: ng test --watch=false --browsers=ChromeHeadless
      working-directory: ${{env.working-directory}}

