name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1

    - run: ls -l
    - run: python --version
    - run: cd ./backend
    - run: pip3 install -r requirements.txt
    
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3

    - name: MongoDB as docker
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 4.2.3

    - run: docker ps
    - run: docker inspect $(docker ps -q)
    - run: pytest