name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    
    - run: pip3 install requirements.txt
    
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3

    - name: Start MongoDB
      uses: superchargejs/mongodb-github-action@v1
      with:
        mongodb-version: 4.2.3
        
    - name: Pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0
